CREATE TABLE "users" (
                         "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "username" varchar NOT NULL,
                         "password" varchar(10) NOT NULL,
                         "email" varchar(50) NOT NULL
);

CREATE TABLE "movies" (
                          "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "title" varchar NOT NULL,
                          "overview" varchar NOT NULL,
                          "release_date" date NOT NULL,
                          "poster_url" varchar NOT NULL
);

CREATE TABLE "ratings" (
                           "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "score" int,
                           "user_id" int,
                           "movie_id" int
);

CREATE INDEX ON "users" ("id");

CREATE INDEX ON "movies" ("id");

ALTER TABLE "ratings" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "ratings" ADD FOREIGN KEY ("movie_id") REFERENCES "movies" ("id");
