CREATE TABLE "users" (
  "username" varchar PRIMARY KEY,
  "password" varchar(10) NOT NULL,
  "email" varchar(50) NOT NULL
);

CREATE TABLE "movies" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "overview" varchar NOT NULL,
  "release_date" date NOT NULL,
  "poster_url" varchar NOT NULL
);

CREATE TABLE "ratings" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "score" int,
  "user_username" varchar,
  "movie_id" int
);

CREATE INDEX ON "users" ("username");

CREATE INDEX ON "movies" ("id");

ALTER TABLE "ratings" ADD FOREIGN KEY ("user_username") REFERENCES "users" ("username");

ALTER TABLE "ratings" ADD FOREIGN KEY ("movie_id") REFERENCES "movies" ("id");
