// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"database/sql"
	"time"
)

type Movie struct {
	ID          int32     `json:"id"`
	Title       string    `json:"title"`
	Overview    string    `json:"overview"`
	ReleaseDate time.Time `json:"release_date"`
	PosterUrl   string    `json:"poster_url"`
}

type Rating struct {
	ID      int32         `json:"id"`
	Score   sql.NullInt32 `json:"score"`
	UserID  sql.NullInt32 `json:"user_id"`
	MovieID sql.NullInt32 `json:"movie_id"`
}

type User struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}
